#!/usr/bin/env python
# Copyright (c) 2018 Tiger-Workshop Limited. All rights reserved.

import struct
import sys
import os
import threading
import Queue
import json
import urllib
import tempfile
import uuid
import win32com.client
import win32gui
import wx
import wx.adv
import subprocess

# Title String
TITLE = "Chrome Direct Print"
# Version String
VERSION = "2.0.0"
# Debug Switch
DEBUG = False

# On Windows, the default I/O mode is O_TEXT. Set this to O_BINARY
# to avoid unwanted modifications of the input/output streams.
if sys.platform == "win32":
    import msvcrt
    msvcrt.setmode(sys.__stdin__.fileno(), os.O_BINARY)
    msvcrt.setmode(sys.__stdout__.fileno(), os.O_BINARY)

# Helper function that sends a message to the webapp.
def send_message(message):
    # Write message size.
    sys.__stdout__.write(struct.pack('I', len(message)))
    # Write the message itself.
    sys.__stdout__.write(message)
    sys.__stdout__.flush()

# Thread that reads messages from the webapp.
def read_thread_func(queue):
    while 1:
    # Read the message length (first 4 bytes).
        text_length_bytes = sys.__stdin__.read(4)

        if len(text_length_bytes) == 0:
            if queue:
                queue.put(None)
            sys.exit(0)

        try:
            # Unpack message length as 4 byte integer.
            text_length = struct.unpack('i', text_length_bytes)[0]

            # Read the text (JSON object) of the message.
            text = sys.__stdin__.read(text_length).decode('utf-8')
        except:
            text = ''
            print('Decode error: %s' % text)

        if queue:
            queue.put(text)
        else:
            # Procsss Input
            handler = MessageHandler(None)
            handler.handle(text)

class MessageHandler():
    def __init__(self, window):
        self.window = window

    def log(self, message):
        if self.window:
            self.window.log(message)

    def response(self, message):
        self.log(">> %s" % message)
        send_message(message)
        
    def show(self, message, time = 1000):
        if self.window:
            self.log(message)
            self.window.showMessage(message, time)
            
    def close(self):
        if self.window:
            self.window.onClose(None)

    def handle(self, message):

        self.log("<< %s" % message)
        data = json.loads(message)

        try:
            if not 'action' in data:
                raise ValueError('action required')

            if data['action'] == 'print':
                pdf_path = tempfile.gettempdir() + "/" + str(uuid.uuid4()) + ".pdf"

                if 'printer' in data and data['printer'] != False:
                    printer = data['printer']
                else:
                    printer = ''
                
                if 'url' in data:
                    self.show("Printing from %s to %s" % (data['url'], printer))
                    urllib.urlretrieve(data['url'], pdf_path)
                    self.log("PDF downloaded from %s to %s" % (data['url'], pdf_path))
                else:
                    raise ValueError('url required')
                    
                status = subprocess.call(["PDFtoPrinter.exe", pdf_path, printer])
                self.log("PDFtoPrinter.exe called with status: %s" % status)

                # OK Response
                self.response(json.dumps({'status': status}))
                
                if DEBUG == False:
                    wx.CallLater(3000, self.close)
                
            elif data['action'] == 'list_printer':
                strComputer = "."
                objWMIService = win32com.client.Dispatch("WbemScripting.SWbemLocator")
                objSWbemServices = objWMIService.ConnectServer(strComputer,"root\cimv2")
                colItems = objSWbemServices.ExecQuery("Select * from Win32_PrinterConfiguration")

                printers = []

                for objItem in colItems:
                    printers.append(objItem.Name)

                self.response(json.dumps({'status': 0, 'action': 'list_printer', 'items': printers}))
            elif data['action'] == 'version':
                self.response(json.dumps({'status': 0, 'action': 'version', 'value': VERSION}))
            elif data['action'] == 'bye':
                if DEBUG == False:
                    self.close()
            else:
                raise ValueError('Unknown action: %s' % data['action'])


        except Exception as e:
            # Error Response
            self.response(json.dumps({'status': 1, 'message': str(e)}))
    
    def enum_callback(self, hwnd, results):
        self.winlist.append((hwnd, win32gui.GetWindowText(hwnd)))
            

class MainWindow(wx.Frame):
    def __init__(self, parent, title, queue):
        self.queue = queue
        self.parent = parent
        self.handler = MessageHandler(self)
        
        wx.Frame.__init__(self, parent, title=title, size=(640,480))
        self.Bind(wx.EVT_CLOSE, self.onClose)
        
        self.text = wx.TextCtrl(self, -1,
                                style=wx.TE_MULTILINE|wx.BORDER_SUNKEN|wx.TE_READONLY|
                                wx.TE_RICH2, size=(640,480))
                                
        if DEBUG == True:
            self.Show(True)

        wx.CallLater(100, self.processMessages)
    
    def onIconClick(self, event):
        self.Show(True)
    
    def onClose(self, event):
        if self.icon:
            self.icon.Destroy()
        self.Destroy()
    
    def setIcon(self, icon):
        self.icon = icon
        self.icon.Bind(wx.adv.EVT_TASKBAR_LEFT_UP, self.onIconClick)
        self.icon.Bind(wx.adv.EVT_TASKBAR_RIGHT_UP, self.onIconClick)
    
    def showMessage(self, message, time = 1000):
        if self.icon:
            self.icon.ShowBalloon(TITLE, message, time)
    
    def processMessages(self):
        while not self.queue.empty():

            message = self.queue.get_nowait()
            if message == None:
                self.quit()
                return

            # Procsss Input
            self.handler.handle(message)

        wx.CallLater(100, self.processMessages)

    def log(self, message):
        self.text.AppendText(message + "\n")


# Start the App
app = wx.App(False)
queue = Queue.Queue()

# main window
main_window = MainWindow(None, TITLE, queue)

# message queue
thread = threading.Thread(target=read_thread_func, args=(queue,))
thread.daemon = True
thread.start()

# icon object
icon = wx.Icon(os.path.dirname(os.path.realpath(__file__)) + "/icon-128.png", wx.BITMAP_TYPE_PNG)

# taskbar icon
taskbaricon = wx.adv.TaskBarIcon()
taskbaricon.SetIcon(icon, TITLE)

main_window.setIcon(taskbaricon)

sys.stdin = open(os.devnull, 'r')
sys.stdout = open(os.devnull, 'w')
sys.stderr = open(os.devnull, 'w')

app.MainLoop()
